#!/bin/bash
set -e

# Update restic to latest version
restic self-update

# Define alias for restic command so we don't have to specify the SFTP option

echo "alias restic='restic -o ${RESTIC_OPTION}'" >> /root/.resticrc
echo "alias restic_backup='restic -H ${HOST} -o ${RESTIC_OPTION} --exclude-file=/root/.restic/restic-excludes.txt'" >> /root/.resticrc
echo "source /root/.resticrc" >> /root/.bashrc
